src += $(wildcard $(root)/libs/zlib/*.c) \
	   $(wildcard $(root)/libs/libpng/*.c) \
	   $(wildcard $(root)/libs/libjpeg/*.c) \
	   $(wildcard $(root)/libs/imago2/*.c) \
	   $(wildcard $(root)/libs/vmath/*.c) \
	   $(wildcard $(root)/libs/drawtext/*.c)

ccsrc += $(wildcard $(root)/libs/goatkit/*.cc)

incdir += -I$(root)/libs -I$(root)/libs/imago2 -I$(root)/libs/zlib \
		  -I$(root)/libs/libpng -I$(root)/libs/libjpeg \
		  -I$(root)/libs/vmath -I$(root)/libs/drawtext
