src += $(wildcard libs/zlib/*.c) \
	   $(wildcard libs/libpng/*.c) \
	   $(wildcard libs/libjpeg/*.c) \
	   $(wildcard libs/imago2/*.c) \
	   $(wildcard libs/vmath/*.c)

incdir += -Ilibs/imago2 -Ilibs/zlib -Ilibs/libpng -Ilibs/libjpeg -Ilibs/vmath
