src += $(wildcard libs/zlib/*.c) \
	   $(wildcard libs/libpng/*.c) \
	   $(wildcard libs/libjpeg/*.c) \
	   $(wildcard libs/imago2/*.c) \
	   $(wildcard libs/vmath/*.c) \
	   $(wildcard libs/drawtext/*.c)

ccsrc += $(wildcard libs/goatkit/*.cc)

incdir += -Ilibs -Ilibs/imago2 -Ilibs/zlib -Ilibs/libpng -Ilibs/libjpeg \
		  -Ilibs/vmath -Ilibs/drawtext
